//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HartAnalyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HartAnalyzer.Properties.ResourcesMain", typeof(ResourcesMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command 0.
        /// </summary>
        public static string RibbonCommand0 {
            get {
                return ResourceManager.GetString("RibbonCommand0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command 1.
        /// </summary>
        public static string RibbonCommand1 {
            get {
                return ResourceManager.GetString("RibbonCommand1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command 2.
        /// </summary>
        public static string RibbonCommand2 {
            get {
                return ResourceManager.GetString("RibbonCommand2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string RibbonCommands {
            get {
                return ResourceManager.GetString("RibbonCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurieren.
        /// </summary>
        public static string RibbonConfigurateConnection {
            get {
                return ResourceManager.GetString("RibbonConfigurateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung.
        /// </summary>
        public static string RibbonConnection {
            get {
                return ResourceManager.GetString("RibbonConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string RibbonConnectionCommandClose {
            get {
                return ResourceManager.GetString("RibbonConnectionCommandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string RibbonConnectionCommandOpen {
            get {
                return ResourceManager.GetString("RibbonConnectionCommandOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string RibbonStart {
            get {
                return ResourceManager.GetString("RibbonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansicht.
        /// </summary>
        public static string RibbonView {
            get {
                return ResourceManager.GetString("RibbonView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string RibbonViewFilterAddressToggleButton {
            get {
                return ResourceManager.GetString("RibbonViewFilterAddressToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfsumme.
        /// </summary>
        public static string RibbonViewFilterChecksumToggleButton {
            get {
                return ResourceManager.GetString("RibbonViewFilterChecksumToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string RibbonViewFilterCommandToggleButton {
            get {
                return ResourceManager.GetString("RibbonViewFilterCommandToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten.
        /// </summary>
        public static string RibbonViewFilterDataToggleButton {
            get {
                return ResourceManager.GetString("RibbonViewFilterDataToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter.
        /// </summary>
        public static string RibbonViewFilterDelimiterToggleButton {
            get {
                return ResourceManager.GetString("RibbonViewFilterDelimiterToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string RibbonViewFilterGroup {
            get {
                return ResourceManager.GetString("RibbonViewFilterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Länge.
        /// </summary>
        public static string RibbonViewFilterLengthToggleButton {
            get {
                return ResourceManager.GetString("RibbonViewFilterLengthToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Präambeln.
        /// </summary>
        public static string RibbonViewFilterPreamblesToggleButton {
            get {
                return ResourceManager.GetString("RibbonViewFilterPreamblesToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Code.
        /// </summary>
        public static string RibbonViewFilterResponseCodeToggleButton {
            get {
                return ResourceManager.GetString("RibbonViewFilterResponseCodeToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeit.
        /// </summary>
        public static string RibbonViewFilterTimeToggleButton {
            get {
                return ResourceManager.GetString("RibbonViewFilterTimeToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string RibbonViewFilterTypeToggleButton {
            get {
                return ResourceManager.GetString("RibbonViewFilterTypeToggleButton", resourceCulture);
            }
        }
    }
}
